### ISSUE TITLE
感谢，已经在雷凌上用上了👍

### ISSUE THREAD

**Issue by 0312birdzhang** [GhostClock/GC-Camry-iOS#1]
但是不知道是车型不同返回json不同的原因还是写错了，感觉这里的```${warningMsg}```应该是```carInfoData.warningMsg```吧。

https://github.com/GhostClock/GC-Camry-iOS/blob/3d35b2f0cd4b6565088d9542df7491660f346e0f/GC-Camry-iOS.js#L955

其他的我只改了一下车型名称，还有经纬度不知道为啥获取不到，`result["result"]`是空对象，这里我没仔细调一下。 https://github.com/GhostClock/GC-Camry-iOS/blob/3d35b2f0cd4b6565088d9542df7491660f346e0f/GC-Camry-iOS.js#L993

感觉可以做成通用的啊，其他车型应该不用怎么改就可以用了。再次感谢！！！

**Comment by GhostClock** [comment]
感谢指正，develop已经修改，欢迎体验，再测试几天没问题就合到master
